package odtest.javax.mail;

import javax.mail.*;
import javax.mail.internet.*;
import javax.management.RuntimeErrorException;
import javax.xml.transform.sax.TemplatesHandler;

import freemarker.core.*;
import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import freemarker.template.TemplateExceptionHandler;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import org.springframework.ui.freemarker.FreeMarkerTemplateUtils;

public class JavaMailTest {

	public JavaMailTest() {
		// TODO Auto-generated constructor stub
	}

	
	public static void main(String[] args) throws Exception {
		final String username = "";
		final String password = "";
		
		Properties props = new Properties();
		//props.setProperty("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.auth", "true");
		
		Session session = Session.getDefaultInstance(props, /*new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		}*/null);
		
		try {
			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("waodla@gmail.com"));
			message.addRecipient(Message.RecipientType.TO, new InternetAddress("od710122@gmail.com"));
			message.setSubject("Testing Subject");
			
			Configuration templateConfig = new Configuration(Configuration.VERSION_2_3_23);
			templateConfig.setClassForTemplateLoading(JavaMailTest.class, "/templates/");
			templateConfig.setDefaultEncoding("UTF-8");
			templateConfig.setTemplateExceptionHandler(TemplateExceptionHandler.RETHROW_HANDLER);
			Template template = templateConfig.getTemplate("test_template.ftl");
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("title", "Freemarker Template Test");
			map.put("bodyTitle",	"Body Title");
			map.put("message", "This is a mail generated by Freemarker,");
			String content = FreeMarkerTemplateUtils.processTemplateIntoString(template, map);
			
			
			message.setContent(content, "text/html");
			
			Transport transport = session.getTransport("smtp");
			transport.connect("smtp.gmail.com", username, password);
			transport.sendMessage(message, message.getAllRecipients());
			transport.close();
			
			System.out.println("Done");
		} catch (MessagingException  e) {
			throw new RuntimeException(e);
		} 
	}
}
